#!/usr/bin/env zsh

# Reference: https://mjones44.medium.com/storing-dotfiles-in-a-git-repository-53f765c0005d

git clone --bare git@github.com:inabsentia/dotfiles.git $HOME/.dotfiles

# define config alias locally since the dotfiles
# aren't installed on the system yet
function dfc {
  git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

# create a directory to backup existing dotfiles to
mkdir -p .dotfiles-backup

dfc checkout

if [ $? = 0 ]; then
  echo "Checked out dotfiles from git@github.com:inabsentia/dotfiles.git"
else
  echo "Moving existing dotfiles to ~/.dotfiles-backup"
    dfc checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi

# checkout dotfiles from repo
dfc checkout
dfc config.local status.showUntrackedFiles no

# Install Homebrew
NON_INTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Set up ZSH
git clone --recursive https://github.com/inabsentia/prezto.git "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/.zprezto"

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export ZDOTDIR="${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

source "$ZDOTDIR/.zshenv"

# Install command-line tools
# touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
# softwareupdate -i -a
# rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
xcode-select --install || true

brew bundle

# Link Emacs.app and start service
osascript -e 'tell application "Finder" to make alias file to posix file "/opt/homebrew/opt/emacs-plus@30/Emacs.app" at posix file "/Applications" with properties {name:"Emacs.app"}'
brew services start d12frosted/emacs-plus/emacs-plus@30

# Set up Doom Emacs
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
$HOME/config/emacs/bin/doom install
